name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: '3.10'
    - name: Create and activate environment
      run: |
        conda env create --file environment.yml
        conda activate myenv  # Ensure this matches your environment name in environment.yml
    - name: Lint with flake8
      run: |
        conda install flake8 -n myenv
        conda run -n myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n myenv flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
